# Generated by Django 4.1.4 on 2023-03-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='intcal_respuesta',
            field=models.IntegerField(choices=[[0, 'Default'], [1, 'Pendiente'], [2, 'Activa'], [3, 'Terminada']], default=0),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_apellido',
            field=models.CharField(default='', max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_cargo',
            field=models.CharField(default='', max_length=30, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_imagen',
            field=models.ImageField(upload_to='marcas', verbose_name='Logotipo Marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_imagen_persona',
            field=models.ImageField(upload_to='marcas', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_mail',
            field=models.CharField(default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_telefono',
            field=models.CharField(default='', max_length=30, verbose_name='Teléfono'),
        ),
    ]
