# Generated by Django 4.1.4 on 2023-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_intcal_respuesta_campana_cam_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='cam_dias',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='campana',
            name='cam_medallas',
            field=models.IntegerField(default=None),
        ),
    ]
