# Generated by Django 4.1.4 on 2023-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_campana_cam_dias_alter_campana_cam_medallas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='cam_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campana',
            name='cam_medallas',
            field=models.IntegerField(default=0),
        ),
    ]
