# Generated by Django 4.1.4 on 2023-04-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_campana_cam_dias_alter_campana_cam_medallas'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='cam_caracteristicas_recompensa',
            field=models.TextField(null=True, verbose_name='Descripción Recompensa'),
        ),
        migrations.AddField(
            model_name='campana',
            name='cam_imagen_recompensa',
            field=models.ImageField(null=True, upload_to='campanas', verbose_name='Imagen Recompensa'),
        ),
        migrations.AddField(
            model_name='campana',
            name='cam_nom_recompensa',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Recompensa'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='cam_cantidad_recompensas',
            field=models.IntegerField(default=0),
        ),
    ]
