# Generated by Django 4.1.4 on 2023-04-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_campana_cam_caracteristicas_recompensa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='cam_caracteristicas_recompensa',
            field=models.TextField(verbose_name='Descripción Recompensa'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='cam_imagen_recompensa',
            field=models.ImageField(upload_to='campanas', verbose_name='Imagen Recompensa'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='cam_nom_recompensa',
            field=models.CharField(max_length=50, verbose_name='Nombre Recompensa'),
        ),
    ]
