# Generated by Django 4.1.4 on 2023-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_campana_cam_caracteristicas_recompensa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='cam_link_recompensa',
            field=models.CharField(max_length=200, null=True, verbose_name='Enlace más información de la recompensa'),
        ),
    ]
