# Generated by Django 4.1.4 on 2023-04-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_campana_cam_link_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='cam_descripcion_recompensa',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción Recompensa'),
        ),
    ]
