# Generated by Django 4.1.4 on 2023-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_campana_cam_descripcion_recompensa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='cam_caracteristicas_recompensa',
            field=models.TextField(null=True, verbose_name='Características Recompensa'),
        ),
    ]
