# Generated by Django 4.1.4 on 2023-04-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_campana_cam_caracteristicas_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='mar_moda',
            field=models.IntegerField(default=0),
        ),
    ]
