# Generated by Django 4.1.4 on 2023-04-13 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_marca_mar_moda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='mar_moda',
        ),
        migrations.AddField(
            model_name='marca',
            name='mar_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.categoria', verbose_name='Categoría'),
        ),
    ]
