# Generated by Django 4.1.4 on 2023-04-13 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_marca_mar_moda_marca_mar_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='mar_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.categoria', verbose_name='Categoría Marca'),
        ),
    ]
