# Generated by Django 4.1.4 on 2023-04-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_campana_cam_fecha_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='cam_fecha_posteo',
        ),
    ]
