# Generated by Django 4.1.4 on 2023-07-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='int_calificar',
            name='intcal_fecha_int',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='int_compartir',
            name='intcom_fecha_int',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='int_recomendar',
            name='intrec_fecha_int',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
