# Generated by Django 4.1.4 on 2023-08-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_seleccion_categorias_usuario_sel_cat_cat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleccion_categorias_usuario',
            name='sel_cat_cat',
        ),
        migrations.AddField(
            model_name='seleccion_categorias_usuario',
            name='sel_cat_cat',
            field=models.CharField(default='', max_length=200),
        ),
    ]
